### ISSUE TITLE
[NumberGuesser] {0:N1}

### ISSUE THREAD

**Issue by pavel-b-novikov** [yuukos/nsudotnet#3]
Что означает этот модификатор в string.Format? Какие еще вы знаете?

**Comment by yuukos** [comment]
Так число выводится красиво) В целой части выделяются каждые три разряда, а единичка означает, что выводится 1 разряд после запятой

**Comment by yuukos** [comment]
Есть еще модификаторы для вывода целочисленных (также можно контролировать количество выводимых разрядов), в виде экспоненты, шестнадцатеричный есть, вроде когда писал лабу даже нагуглил вывод валюты

**Comment by pavel-b-novikov** [comment]
Отлично. Это знать хорошо и полезно.
