### ISSUE TITLE
[Enigma] Array.FindIndex

### ISSUE THREAD

**Issue by pavel-b-novikov** [yuukos/nsudotnet#4]
```Array.FindIndex(ALGORITHMS, a => a.ToLower() == algorithmName) != -1```
Серьезно? Алексей, вы слишком много пишете на javascript. Найдите более ласкающий слух метод

**Comment by yuukos** [comment]
Никогда на JS не писал)))

**Comment by yuukos** [comment]
Сейчас вроде строчка попроще выглядит (надеюсь, будет усерднее ласкать))

**Comment by pavel-b-novikov** [comment]
Ну.. Conains куда ни шло. Я думал что вы заюзаете .Any, но ладно
